export TOP_DIR = $(PWD)/..
export APP_DIR = $(TOP_DIR)/db_struct_generator
export APP_BINDIR = $(TOP_DIR)/bin/db_struct_generator
export APP_EXE = db_struct_generator
export BOOST_LIBS = -lboost_system -lboost_thread
include $(TOP_DIR)/common.mk
