// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: error.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from error.proto</summary>
public static partial class ErrorReflection {

  #region Descriptor
  /// <summary>File descriptor for error.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ErrorReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CgtlcnJvci5wcm90byIvCghNc2dFcnJvchIjCgplcnJvcl9jb2RlGAEgASgO",
          "Mg8uUHJvdG9FcnJvclR5cGUq+wUKDlByb3RvRXJyb3JUeXBlEhQKEFBST1RP",
          "X0VSUk9SX05PTkUQABIhCh1QUk9UT19FUlJPUl9NU0dfREFUQV9JTlZBTElB",
          "RBABEiEKHVBST1RPX0VSUk9SX01TR19IQU5ETEVfRkFJTEVEEAISJQohUFJP",
          "VE9fRVJST1JfU0VSVkVSX0lOVEVSTkFMX0VSUk9SEAMSMQotUFJPVE9fRVJS",
          "T1JfTE9HSU5fQUNDT1VOVF9PUl9QQVNTV09SRF9JTlZBTElEEGQSLAooUFJP",
          "VE9fRVJST1JfTE9HSU5fVkVSSUZZX0FDQ09VTlRfVElNRU9VVBBlEh4KGlBS",
          "T1RPX0VSUk9SX0xPR0lOX1JFUEVBVEVEEGYSIgoeUFJPVE9fRVJST1JfTE9H",
          "SU5fREFUQV9JTlZBTElEEGcSLQopUFJPVE9fRVJST1JfTE9HSU5fR0FNRV9T",
          "RVJWRVJfTUFJTlRFTkFOQ0UQaBIeChlQUk9UT19FUlJPUl9HRVRfUk9MRV9O",
          "T05FEJYBEiIKHVBST1RPX0VSUk9SX0VOVEVSX0dBTUVfRkFJTEVEEMgBEiQK",
          "H1BST1RPX0VSUk9SX0VOVEVSX0dBTUVfUkVQRUFURUQQyQESKwomUFJPVE9f",
          "RVJST1JfRU5URVJfR0FNRV9JTlZBTElEX0FDQ09VTlQQygESKwomUFJPVE9f",
          "RVJST1JfRU5URVJfR0FNRV9JTlZBTElEX1NFU1NJT04QywESMAorUFJPVE9f",
          "RVJST1JfRU5URVJfR0FNRV9QTEFZRVJfQ09VTlRfTUFYSU1VTRDMARIoCiNQ",
          "Uk9UT19FUlJPUl9FTlRFUl9HQU1FX1JPTEVfSU5WQUxJRBDNARIpCiRQUk9U",
          "T19FUlJPUl9SRUNPTk5fQUNDT1VOVF9OT1RfRk9VTkQQ0gESJwoiUFJPVE9f",
          "RVJST1JfUkVDT05OX1NFU1NJT05fSU5WQUxJRBDTARIeChlQUk9UT19FUlJP",
          "Ul9SRUNPTk5fRkFJTEVEENQBYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::ProtoErrorType), }, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::MsgError), global::MsgError.Parser, new[]{ "ErrorCode" }, null, null, null)
        }));
  }
  #endregion

}
#region Enums
public enum ProtoErrorType {
  [pbr::OriginalName("PROTO_ERROR_NONE")] ProtoErrorNone = 0,
  [pbr::OriginalName("PROTO_ERROR_MSG_DATA_INVALIAD")] ProtoErrorMsgDataInvaliad = 1,
  [pbr::OriginalName("PROTO_ERROR_MSG_HANDLE_FAILED")] ProtoErrorMsgHandleFailed = 2,
  [pbr::OriginalName("PROTO_ERROR_SERVER_INTERNAL_ERROR")] ProtoErrorServerInternalError = 3,
  [pbr::OriginalName("PROTO_ERROR_LOGIN_ACCOUNT_OR_PASSWORD_INVALID")] ProtoErrorLoginAccountOrPasswordInvalid = 100,
  [pbr::OriginalName("PROTO_ERROR_LOGIN_VERIFY_ACCOUNT_TIMEOUT")] ProtoErrorLoginVerifyAccountTimeout = 101,
  [pbr::OriginalName("PROTO_ERROR_LOGIN_REPEATED")] ProtoErrorLoginRepeated = 102,
  [pbr::OriginalName("PROTO_ERROR_LOGIN_DATA_INVALID")] ProtoErrorLoginDataInvalid = 103,
  [pbr::OriginalName("PROTO_ERROR_LOGIN_GAME_SERVER_MAINTENANCE")] ProtoErrorLoginGameServerMaintenance = 104,
  [pbr::OriginalName("PROTO_ERROR_GET_ROLE_NONE")] ProtoErrorGetRoleNone = 150,
  [pbr::OriginalName("PROTO_ERROR_ENTER_GAME_FAILED")] ProtoErrorEnterGameFailed = 200,
  [pbr::OriginalName("PROTO_ERROR_ENTER_GAME_REPEATED")] ProtoErrorEnterGameRepeated = 201,
  [pbr::OriginalName("PROTO_ERROR_ENTER_GAME_INVALID_ACCOUNT")] ProtoErrorEnterGameInvalidAccount = 202,
  [pbr::OriginalName("PROTO_ERROR_ENTER_GAME_INVALID_SESSION")] ProtoErrorEnterGameInvalidSession = 203,
  [pbr::OriginalName("PROTO_ERROR_ENTER_GAME_PLAYER_COUNT_MAXIMUM")] ProtoErrorEnterGamePlayerCountMaximum = 204,
  [pbr::OriginalName("PROTO_ERROR_ENTER_GAME_ROLE_INVALID")] ProtoErrorEnterGameRoleInvalid = 205,
  [pbr::OriginalName("PROTO_ERROR_RECONN_ACCOUNT_NOT_FOUND")] ProtoErrorReconnAccountNotFound = 210,
  [pbr::OriginalName("PROTO_ERROR_RECONN_SESSION_INVALID")] ProtoErrorReconnSessionInvalid = 211,
  [pbr::OriginalName("PROTO_ERROR_RECONN_FAILED")] ProtoErrorReconnFailed = 212,
}

#endregion

#region Messages
public sealed partial class MsgError : pb::IMessage<MsgError> {
  private static readonly pb::MessageParser<MsgError> _parser = new pb::MessageParser<MsgError>(() => new MsgError());
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<MsgError> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ErrorReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public MsgError() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public MsgError(MsgError other) : this() {
    errorCode_ = other.errorCode_;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public MsgError Clone() {
    return new MsgError(this);
  }

  /// <summary>Field number for the "error_code" field.</summary>
  public const int ErrorCodeFieldNumber = 1;
  private global::ProtoErrorType errorCode_ = 0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::ProtoErrorType ErrorCode {
    get { return errorCode_; }
    set {
      errorCode_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as MsgError);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(MsgError other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (ErrorCode != other.ErrorCode) return false;
    return true;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (ErrorCode != 0) hash ^= ErrorCode.GetHashCode();
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (ErrorCode != 0) {
      output.WriteRawTag(8);
      output.WriteEnum((int) ErrorCode);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (ErrorCode != 0) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ErrorCode);
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(MsgError other) {
    if (other == null) {
      return;
    }
    if (other.ErrorCode != 0) {
      ErrorCode = other.ErrorCode;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          input.SkipLastField();
          break;
        case 8: {
          errorCode_ = (global::ProtoErrorType) input.ReadEnum();
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
