// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: error.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from error.proto</summary>
public static partial class ErrorReflection {

  #region Descriptor
  /// <summary>File descriptor for error.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ErrorReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CgtlcnJvci5wcm90byr7BQoOUHJvdG9FcnJvclR5cGUSFAoQUFJPVE9fRVJS",
          "T1JfTk9ORRAAEiEKHVBST1RPX0VSUk9SX01TR19EQVRBX0lOVkFMSUFEEAES",
          "IQodUFJPVE9fRVJST1JfTVNHX0hBTkRMRV9GQUlMRUQQAhIlCiFQUk9UT19F",
          "UlJPUl9TRVJWRVJfSU5URVJOQUxfRVJST1IQAxIxCi1QUk9UT19FUlJPUl9M",
          "T0dJTl9BQ0NPVU5UX09SX1BBU1NXT1JEX0lOVkFMSUQQZBIsCihQUk9UT19F",
          "UlJPUl9MT0dJTl9WRVJJRllfQUNDT1VOVF9USU1FT1VUEGUSHgoaUFJPVE9f",
          "RVJST1JfTE9HSU5fUkVQRUFURUQQZhIiCh5QUk9UT19FUlJPUl9MT0dJTl9E",
          "QVRBX0lOVkFMSUQQZxItCilQUk9UT19FUlJPUl9MT0dJTl9HQU1FX1NFUlZF",
          "Ul9NQUlOVEVOQU5DRRBoEh4KGVBST1RPX0VSUk9SX0dFVF9ST0xFX05PTkUQ",
          "lgESIgodUFJPVE9fRVJST1JfRU5URVJfR0FNRV9GQUlMRUQQyAESJAofUFJP",
          "VE9fRVJST1JfRU5URVJfR0FNRV9SRVBFQVRFRBDJARIrCiZQUk9UT19FUlJP",
          "Ul9FTlRFUl9HQU1FX0lOVkFMSURfQUNDT1VOVBDKARIrCiZQUk9UT19FUlJP",
          "Ul9FTlRFUl9HQU1FX0lOVkFMSURfU0VTU0lPThDLARIwCitQUk9UT19FUlJP",
          "Ul9FTlRFUl9HQU1FX1BMQVlFUl9DT1VOVF9NQVhJTVVNEMwBEigKI1BST1RP",
          "X0VSUk9SX0VOVEVSX0dBTUVfUk9MRV9JTlZBTElEEM0BEikKJFBST1RPX0VS",
          "Uk9SX1JFQ09OTl9BQ0NPVU5UX05PVF9GT1VORBDSARInCiJQUk9UT19FUlJP",
          "Ul9SRUNPTk5fU0VTU0lPTl9JTlZBTElEENMBEh4KGVBST1RPX0VSUk9SX1JF",
          "Q09OTl9GQUlMRUQQ1AFiBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::ProtoErrorType), }, null));
  }
  #endregion

}
#region Enums
public enum ProtoErrorType {
  [pbr::OriginalName("PROTO_ERROR_NONE")] ProtoErrorNone = 0,
  [pbr::OriginalName("PROTO_ERROR_MSG_DATA_INVALIAD")] ProtoErrorMsgDataInvaliad = 1,
  [pbr::OriginalName("PROTO_ERROR_MSG_HANDLE_FAILED")] ProtoErrorMsgHandleFailed = 2,
  [pbr::OriginalName("PROTO_ERROR_SERVER_INTERNAL_ERROR")] ProtoErrorServerInternalError = 3,
  [pbr::OriginalName("PROTO_ERROR_LOGIN_ACCOUNT_OR_PASSWORD_INVALID")] ProtoErrorLoginAccountOrPasswordInvalid = 100,
  [pbr::OriginalName("PROTO_ERROR_LOGIN_VERIFY_ACCOUNT_TIMEOUT")] ProtoErrorLoginVerifyAccountTimeout = 101,
  [pbr::OriginalName("PROTO_ERROR_LOGIN_REPEATED")] ProtoErrorLoginRepeated = 102,
  [pbr::OriginalName("PROTO_ERROR_LOGIN_DATA_INVALID")] ProtoErrorLoginDataInvalid = 103,
  [pbr::OriginalName("PROTO_ERROR_LOGIN_GAME_SERVER_MAINTENANCE")] ProtoErrorLoginGameServerMaintenance = 104,
  [pbr::OriginalName("PROTO_ERROR_GET_ROLE_NONE")] ProtoErrorGetRoleNone = 150,
  [pbr::OriginalName("PROTO_ERROR_ENTER_GAME_FAILED")] ProtoErrorEnterGameFailed = 200,
  [pbr::OriginalName("PROTO_ERROR_ENTER_GAME_REPEATED")] ProtoErrorEnterGameRepeated = 201,
  [pbr::OriginalName("PROTO_ERROR_ENTER_GAME_INVALID_ACCOUNT")] ProtoErrorEnterGameInvalidAccount = 202,
  [pbr::OriginalName("PROTO_ERROR_ENTER_GAME_INVALID_SESSION")] ProtoErrorEnterGameInvalidSession = 203,
  [pbr::OriginalName("PROTO_ERROR_ENTER_GAME_PLAYER_COUNT_MAXIMUM")] ProtoErrorEnterGamePlayerCountMaximum = 204,
  [pbr::OriginalName("PROTO_ERROR_ENTER_GAME_ROLE_INVALID")] ProtoErrorEnterGameRoleInvalid = 205,
  [pbr::OriginalName("PROTO_ERROR_RECONN_ACCOUNT_NOT_FOUND")] ProtoErrorReconnAccountNotFound = 210,
  [pbr::OriginalName("PROTO_ERROR_RECONN_SESSION_INVALID")] ProtoErrorReconnSessionInvalid = 211,
  [pbr::OriginalName("PROTO_ERROR_RECONN_FAILED")] ProtoErrorReconnFailed = 212,
}

#endregion


#endregion Designer generated code
