export TOP_DIR = $(PWD)/..
export APP_DIR = $(TOP_DIR)/config_server
export APP_BINDIR = $(TOP_DIR)/bin/config_server
export APP_EXE = config_server
export BOOST_LIBS = -lboost_system -lboost_coroutine -lboost_context -lboost_thread
include $(TOP_DIR)/common.mk
