export TOP_DIR = $(PWD)/..
export SERVER_DIR = $(TOP_DIR)/login_server
export SERVER_BINDIR = $(TOP_DIR)/bin/login_server
export SERVER_EXE = login_server
export BOOST_LIBS = -lboost_system -lboost_thread
include $(TOP_DIR)/common.mk
