export TOP_DIR = $(PWD)/..
export APP_DIR = $(TOP_DIR)/gate_server
export APP_BINDIR = $(TOP_DIR)/bin/gate_server
export APP_EXE = gate_server
export BOOST_LIBS = -lboost_system -lboost_thread
include $(TOP_DIR)/common.mk
