// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: db_struct.proto

#ifndef PROTOBUF_db_5fstruct_2eproto__INCLUDED
#define PROTOBUF_db_5fstruct_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3002000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3002000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
class DBActivitiesDataList;
class DBActivitiesDataListDefaultTypeInternal;
extern DBActivitiesDataListDefaultTypeInternal _DBActivitiesDataList_default_instance_;
class DBActivityData;
class DBActivityDataDefaultTypeInternal;
extern DBActivityDataDefaultTypeInternal _DBActivityData_default_instance_;
class DBDailyTaskData;
class DBDailyTaskDataDefaultTypeInternal;
extern DBDailyTaskDataDefaultTypeInternal _DBDailyTaskData_default_instance_;
class DBDailyTaskDataList;
class DBDailyTaskDataListDefaultTypeInternal;
extern DBDailyTaskDataListDefaultTypeInternal _DBDailyTaskDataList_default_instance_;
class DBItemData;
class DBItemDataDefaultTypeInternal;
extern DBItemDataDefaultTypeInternal _DBItemData_default_instance_;
class DBItemDataList;
class DBItemDataListDefaultTypeInternal;
extern DBItemDataListDefaultTypeInternal _DBItemDataList_default_instance_;
class DBSkillData;
class DBSkillDataDefaultTypeInternal;
extern DBSkillDataDefaultTypeInternal _DBSkillData_default_instance_;
class DBSkillDataList;
class DBSkillDataListDefaultTypeInternal;
extern DBSkillDataListDefaultTypeInternal _DBSkillDataList_default_instance_;
class DBTaskData;
class DBTaskDataDefaultTypeInternal;
extern DBTaskDataDefaultTypeInternal _DBTaskData_default_instance_;
class DBTaskDataList;
class DBTaskDataListDefaultTypeInternal;
extern DBTaskDataListDefaultTypeInternal _DBTaskDataList_default_instance_;

namespace protobuf_db_5fstruct_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_db_5fstruct_2eproto

// ===================================================================

class DBItemData : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:DBItemData) */ {
 public:
  DBItemData();
  virtual ~DBItemData();

  DBItemData(const DBItemData& from);

  inline DBItemData& operator=(const DBItemData& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DBItemData& default_instance();

  static inline const DBItemData* internal_default_instance() {
    return reinterpret_cast<const DBItemData*>(
               &_DBItemData_default_instance_);
  }

  void Swap(DBItemData* other);

  // implements Message ----------------------------------------------

  inline DBItemData* New() const PROTOBUF_FINAL { return New(NULL); }

  DBItemData* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const DBItemData& from);
  void MergeFrom(const DBItemData& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(DBItemData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int64 unique_id = 2;
  void clear_unique_id();
  static const int kUniqueIdFieldNumber = 2;
  ::google::protobuf::int64 unique_id() const;
  void set_unique_id(::google::protobuf::int64 value);

  // int32 type_id = 1;
  void clear_type_id();
  static const int kTypeIdFieldNumber = 1;
  ::google::protobuf::int32 type_id() const;
  void set_type_id(::google::protobuf::int32 value);

  // int32 num = 3;
  void clear_num();
  static const int kNumFieldNumber = 3;
  ::google::protobuf::int32 num() const;
  void set_num(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:DBItemData)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int64 unique_id_;
  ::google::protobuf::int32 type_id_;
  ::google::protobuf::int32 num_;
  mutable int _cached_size_;
  friend struct protobuf_db_5fstruct_2eproto::TableStruct;
};
// -------------------------------------------------------------------


// -------------------------------------------------------------------

class DBItemDataList : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:DBItemDataList) */ {
 public:
  DBItemDataList();
  virtual ~DBItemDataList();

  DBItemDataList(const DBItemDataList& from);

  inline DBItemDataList& operator=(const DBItemDataList& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DBItemDataList& default_instance();

  static inline const DBItemDataList* internal_default_instance() {
    return reinterpret_cast<const DBItemDataList*>(
               &_DBItemDataList_default_instance_);
  }

  void Swap(DBItemDataList* other);

  // implements Message ----------------------------------------------

  inline DBItemDataList* New() const PROTOBUF_FINAL { return New(NULL); }

  DBItemDataList* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const DBItemDataList& from);
  void MergeFrom(const DBItemDataList& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(DBItemDataList* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // map<int64, .DBItemData> items = 1;
  int items_size() const;
  void clear_items();
  static const int kItemsFieldNumber = 1;
  const ::google::protobuf::Map< ::google::protobuf::int64, ::DBItemData >&
      items() const;
  ::google::protobuf::Map< ::google::protobuf::int64, ::DBItemData >*
      mutable_items();

  // @@protoc_insertion_point(class_scope:DBItemDataList)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  typedef ::google::protobuf::internal::MapEntryLite<
      ::google::protobuf::int64, ::DBItemData,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT64,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
      0 >
      DBItemDataList_ItemsEntry;
  ::google::protobuf::internal::MapField<
      ::google::protobuf::int64, ::DBItemData,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT64,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
      0 > items_;
  mutable int _cached_size_;
  friend struct protobuf_db_5fstruct_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class DBSkillData : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:DBSkillData) */ {
 public:
  DBSkillData();
  virtual ~DBSkillData();

  DBSkillData(const DBSkillData& from);

  inline DBSkillData& operator=(const DBSkillData& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DBSkillData& default_instance();

  static inline const DBSkillData* internal_default_instance() {
    return reinterpret_cast<const DBSkillData*>(
               &_DBSkillData_default_instance_);
  }

  void Swap(DBSkillData* other);

  // implements Message ----------------------------------------------

  inline DBSkillData* New() const PROTOBUF_FINAL { return New(NULL); }

  DBSkillData* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const DBSkillData& from);
  void MergeFrom(const DBSkillData& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(DBSkillData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 skill_id = 1;
  void clear_skill_id();
  static const int kSkillIdFieldNumber = 1;
  ::google::protobuf::int32 skill_id() const;
  void set_skill_id(::google::protobuf::int32 value);

  // int32 level = 2;
  void clear_level();
  static const int kLevelFieldNumber = 2;
  ::google::protobuf::int32 level() const;
  void set_level(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:DBSkillData)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 skill_id_;
  ::google::protobuf::int32 level_;
  mutable int _cached_size_;
  friend struct protobuf_db_5fstruct_2eproto::TableStruct;
};
// -------------------------------------------------------------------


// -------------------------------------------------------------------

class DBSkillDataList : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:DBSkillDataList) */ {
 public:
  DBSkillDataList();
  virtual ~DBSkillDataList();

  DBSkillDataList(const DBSkillDataList& from);

  inline DBSkillDataList& operator=(const DBSkillDataList& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DBSkillDataList& default_instance();

  static inline const DBSkillDataList* internal_default_instance() {
    return reinterpret_cast<const DBSkillDataList*>(
               &_DBSkillDataList_default_instance_);
  }

  void Swap(DBSkillDataList* other);

  // implements Message ----------------------------------------------

  inline DBSkillDataList* New() const PROTOBUF_FINAL { return New(NULL); }

  DBSkillDataList* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const DBSkillDataList& from);
  void MergeFrom(const DBSkillDataList& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(DBSkillDataList* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // map<int32, .DBSkillData> skills = 1;
  int skills_size() const;
  void clear_skills();
  static const int kSkillsFieldNumber = 1;
  const ::google::protobuf::Map< ::google::protobuf::int32, ::DBSkillData >&
      skills() const;
  ::google::protobuf::Map< ::google::protobuf::int32, ::DBSkillData >*
      mutable_skills();

  // @@protoc_insertion_point(class_scope:DBSkillDataList)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  typedef ::google::protobuf::internal::MapEntryLite<
      ::google::protobuf::int32, ::DBSkillData,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
      0 >
      DBSkillDataList_SkillsEntry;
  ::google::protobuf::internal::MapField<
      ::google::protobuf::int32, ::DBSkillData,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
      0 > skills_;
  mutable int _cached_size_;
  friend struct protobuf_db_5fstruct_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class DBTaskData : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:DBTaskData) */ {
 public:
  DBTaskData();
  virtual ~DBTaskData();

  DBTaskData(const DBTaskData& from);

  inline DBTaskData& operator=(const DBTaskData& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DBTaskData& default_instance();

  static inline const DBTaskData* internal_default_instance() {
    return reinterpret_cast<const DBTaskData*>(
               &_DBTaskData_default_instance_);
  }

  void Swap(DBTaskData* other);

  // implements Message ----------------------------------------------

  inline DBTaskData* New() const PROTOBUF_FINAL { return New(NULL); }

  DBTaskData* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const DBTaskData& from);
  void MergeFrom(const DBTaskData& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(DBTaskData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 task_id = 1;
  void clear_task_id();
  static const int kTaskIdFieldNumber = 1;
  ::google::protobuf::int32 task_id() const;
  void set_task_id(::google::protobuf::int32 value);

  // int32 task_state = 2;
  void clear_task_state();
  static const int kTaskStateFieldNumber = 2;
  ::google::protobuf::int32 task_state() const;
  void set_task_state(::google::protobuf::int32 value);

  // int32 task_param = 3;
  void clear_task_param();
  static const int kTaskParamFieldNumber = 3;
  ::google::protobuf::int32 task_param() const;
  void set_task_param(::google::protobuf::int32 value);

  // int32 task_param2 = 4;
  void clear_task_param2();
  static const int kTaskParam2FieldNumber = 4;
  ::google::protobuf::int32 task_param2() const;
  void set_task_param2(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:DBTaskData)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 task_id_;
  ::google::protobuf::int32 task_state_;
  ::google::protobuf::int32 task_param_;
  ::google::protobuf::int32 task_param2_;
  mutable int _cached_size_;
  friend struct protobuf_db_5fstruct_2eproto::TableStruct;
};
// -------------------------------------------------------------------


// -------------------------------------------------------------------

class DBTaskDataList : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:DBTaskDataList) */ {
 public:
  DBTaskDataList();
  virtual ~DBTaskDataList();

  DBTaskDataList(const DBTaskDataList& from);

  inline DBTaskDataList& operator=(const DBTaskDataList& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DBTaskDataList& default_instance();

  static inline const DBTaskDataList* internal_default_instance() {
    return reinterpret_cast<const DBTaskDataList*>(
               &_DBTaskDataList_default_instance_);
  }

  void Swap(DBTaskDataList* other);

  // implements Message ----------------------------------------------

  inline DBTaskDataList* New() const PROTOBUF_FINAL { return New(NULL); }

  DBTaskDataList* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const DBTaskDataList& from);
  void MergeFrom(const DBTaskDataList& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(DBTaskDataList* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // map<int32, .DBTaskData> tasks = 1;
  int tasks_size() const;
  void clear_tasks();
  static const int kTasksFieldNumber = 1;
  const ::google::protobuf::Map< ::google::protobuf::int32, ::DBTaskData >&
      tasks() const;
  ::google::protobuf::Map< ::google::protobuf::int32, ::DBTaskData >*
      mutable_tasks();

  // @@protoc_insertion_point(class_scope:DBTaskDataList)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  typedef ::google::protobuf::internal::MapEntryLite<
      ::google::protobuf::int32, ::DBTaskData,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
      0 >
      DBTaskDataList_TasksEntry;
  ::google::protobuf::internal::MapField<
      ::google::protobuf::int32, ::DBTaskData,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
      0 > tasks_;
  mutable int _cached_size_;
  friend struct protobuf_db_5fstruct_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class DBDailyTaskData : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:DBDailyTaskData) */ {
 public:
  DBDailyTaskData();
  virtual ~DBDailyTaskData();

  DBDailyTaskData(const DBDailyTaskData& from);

  inline DBDailyTaskData& operator=(const DBDailyTaskData& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DBDailyTaskData& default_instance();

  static inline const DBDailyTaskData* internal_default_instance() {
    return reinterpret_cast<const DBDailyTaskData*>(
               &_DBDailyTaskData_default_instance_);
  }

  void Swap(DBDailyTaskData* other);

  // implements Message ----------------------------------------------

  inline DBDailyTaskData* New() const PROTOBUF_FINAL { return New(NULL); }

  DBDailyTaskData* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const DBDailyTaskData& from);
  void MergeFrom(const DBDailyTaskData& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(DBDailyTaskData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 task_id = 1;
  void clear_task_id();
  static const int kTaskIdFieldNumber = 1;
  ::google::protobuf::int32 task_id() const;
  void set_task_id(::google::protobuf::int32 value);

  // int32 task_state = 2;
  void clear_task_state();
  static const int kTaskStateFieldNumber = 2;
  ::google::protobuf::int32 task_state() const;
  void set_task_state(::google::protobuf::int32 value);

  // int32 task_param = 3;
  void clear_task_param();
  static const int kTaskParamFieldNumber = 3;
  ::google::protobuf::int32 task_param() const;
  void set_task_param(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:DBDailyTaskData)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 task_id_;
  ::google::protobuf::int32 task_state_;
  ::google::protobuf::int32 task_param_;
  mutable int _cached_size_;
  friend struct protobuf_db_5fstruct_2eproto::TableStruct;
};
// -------------------------------------------------------------------


// -------------------------------------------------------------------

class DBDailyTaskDataList : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:DBDailyTaskDataList) */ {
 public:
  DBDailyTaskDataList();
  virtual ~DBDailyTaskDataList();

  DBDailyTaskDataList(const DBDailyTaskDataList& from);

  inline DBDailyTaskDataList& operator=(const DBDailyTaskDataList& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DBDailyTaskDataList& default_instance();

  static inline const DBDailyTaskDataList* internal_default_instance() {
    return reinterpret_cast<const DBDailyTaskDataList*>(
               &_DBDailyTaskDataList_default_instance_);
  }

  void Swap(DBDailyTaskDataList* other);

  // implements Message ----------------------------------------------

  inline DBDailyTaskDataList* New() const PROTOBUF_FINAL { return New(NULL); }

  DBDailyTaskDataList* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const DBDailyTaskDataList& from);
  void MergeFrom(const DBDailyTaskDataList& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(DBDailyTaskDataList* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // map<int32, .DBDailyTaskData> daily_tasks = 1;
  int daily_tasks_size() const;
  void clear_daily_tasks();
  static const int kDailyTasksFieldNumber = 1;
  const ::google::protobuf::Map< ::google::protobuf::int32, ::DBDailyTaskData >&
      daily_tasks() const;
  ::google::protobuf::Map< ::google::protobuf::int32, ::DBDailyTaskData >*
      mutable_daily_tasks();

  // @@protoc_insertion_point(class_scope:DBDailyTaskDataList)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  typedef ::google::protobuf::internal::MapEntryLite<
      ::google::protobuf::int32, ::DBDailyTaskData,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
      0 >
      DBDailyTaskDataList_DailyTasksEntry;
  ::google::protobuf::internal::MapField<
      ::google::protobuf::int32, ::DBDailyTaskData,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
      0 > daily_tasks_;
  mutable int _cached_size_;
  friend struct protobuf_db_5fstruct_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class DBActivityData : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:DBActivityData) */ {
 public:
  DBActivityData();
  virtual ~DBActivityData();

  DBActivityData(const DBActivityData& from);

  inline DBActivityData& operator=(const DBActivityData& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DBActivityData& default_instance();

  static inline const DBActivityData* internal_default_instance() {
    return reinterpret_cast<const DBActivityData*>(
               &_DBActivityData_default_instance_);
  }

  void Swap(DBActivityData* other);

  // implements Message ----------------------------------------------

  inline DBActivityData* New() const PROTOBUF_FINAL { return New(NULL); }

  DBActivityData* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const DBActivityData& from);
  void MergeFrom(const DBActivityData& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(DBActivityData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 activity_id = 1;
  void clear_activity_id();
  static const int kActivityIdFieldNumber = 1;
  ::google::protobuf::int32 activity_id() const;
  void set_activity_id(::google::protobuf::int32 value);

  // int32 activity_state = 2;
  void clear_activity_state();
  static const int kActivityStateFieldNumber = 2;
  ::google::protobuf::int32 activity_state() const;
  void set_activity_state(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:DBActivityData)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 activity_id_;
  ::google::protobuf::int32 activity_state_;
  mutable int _cached_size_;
  friend struct protobuf_db_5fstruct_2eproto::TableStruct;
};
// -------------------------------------------------------------------


// -------------------------------------------------------------------

class DBActivitiesDataList : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:DBActivitiesDataList) */ {
 public:
  DBActivitiesDataList();
  virtual ~DBActivitiesDataList();

  DBActivitiesDataList(const DBActivitiesDataList& from);

  inline DBActivitiesDataList& operator=(const DBActivitiesDataList& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DBActivitiesDataList& default_instance();

  static inline const DBActivitiesDataList* internal_default_instance() {
    return reinterpret_cast<const DBActivitiesDataList*>(
               &_DBActivitiesDataList_default_instance_);
  }

  void Swap(DBActivitiesDataList* other);

  // implements Message ----------------------------------------------

  inline DBActivitiesDataList* New() const PROTOBUF_FINAL { return New(NULL); }

  DBActivitiesDataList* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const DBActivitiesDataList& from);
  void MergeFrom(const DBActivitiesDataList& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(DBActivitiesDataList* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // map<int32, .DBActivityData> activities = 1;
  int activities_size() const;
  void clear_activities();
  static const int kActivitiesFieldNumber = 1;
  const ::google::protobuf::Map< ::google::protobuf::int32, ::DBActivityData >&
      activities() const;
  ::google::protobuf::Map< ::google::protobuf::int32, ::DBActivityData >*
      mutable_activities();

  // @@protoc_insertion_point(class_scope:DBActivitiesDataList)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  typedef ::google::protobuf::internal::MapEntryLite<
      ::google::protobuf::int32, ::DBActivityData,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
      0 >
      DBActivitiesDataList_ActivitiesEntry;
  ::google::protobuf::internal::MapField<
      ::google::protobuf::int32, ::DBActivityData,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
      0 > activities_;
  mutable int _cached_size_;
  friend struct protobuf_db_5fstruct_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// DBItemData

// int32 type_id = 1;
inline void DBItemData::clear_type_id() {
  type_id_ = 0;
}
inline ::google::protobuf::int32 DBItemData::type_id() const {
  // @@protoc_insertion_point(field_get:DBItemData.type_id)
  return type_id_;
}
inline void DBItemData::set_type_id(::google::protobuf::int32 value) {
  
  type_id_ = value;
  // @@protoc_insertion_point(field_set:DBItemData.type_id)
}

// int64 unique_id = 2;
inline void DBItemData::clear_unique_id() {
  unique_id_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 DBItemData::unique_id() const {
  // @@protoc_insertion_point(field_get:DBItemData.unique_id)
  return unique_id_;
}
inline void DBItemData::set_unique_id(::google::protobuf::int64 value) {
  
  unique_id_ = value;
  // @@protoc_insertion_point(field_set:DBItemData.unique_id)
}

// int32 num = 3;
inline void DBItemData::clear_num() {
  num_ = 0;
}
inline ::google::protobuf::int32 DBItemData::num() const {
  // @@protoc_insertion_point(field_get:DBItemData.num)
  return num_;
}
inline void DBItemData::set_num(::google::protobuf::int32 value) {
  
  num_ = value;
  // @@protoc_insertion_point(field_set:DBItemData.num)
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// DBItemDataList

// map<int64, .DBItemData> items = 1;
inline int DBItemDataList::items_size() const {
  return items_.size();
}
inline void DBItemDataList::clear_items() {
  items_.Clear();
}
inline const ::google::protobuf::Map< ::google::protobuf::int64, ::DBItemData >&
DBItemDataList::items() const {
  // @@protoc_insertion_point(field_map:DBItemDataList.items)
  return items_.GetMap();
}
inline ::google::protobuf::Map< ::google::protobuf::int64, ::DBItemData >*
DBItemDataList::mutable_items() {
  // @@protoc_insertion_point(field_mutable_map:DBItemDataList.items)
  return items_.MutableMap();
}

// -------------------------------------------------------------------

// DBSkillData

// int32 skill_id = 1;
inline void DBSkillData::clear_skill_id() {
  skill_id_ = 0;
}
inline ::google::protobuf::int32 DBSkillData::skill_id() const {
  // @@protoc_insertion_point(field_get:DBSkillData.skill_id)
  return skill_id_;
}
inline void DBSkillData::set_skill_id(::google::protobuf::int32 value) {
  
  skill_id_ = value;
  // @@protoc_insertion_point(field_set:DBSkillData.skill_id)
}

// int32 level = 2;
inline void DBSkillData::clear_level() {
  level_ = 0;
}
inline ::google::protobuf::int32 DBSkillData::level() const {
  // @@protoc_insertion_point(field_get:DBSkillData.level)
  return level_;
}
inline void DBSkillData::set_level(::google::protobuf::int32 value) {
  
  level_ = value;
  // @@protoc_insertion_point(field_set:DBSkillData.level)
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// DBSkillDataList

// map<int32, .DBSkillData> skills = 1;
inline int DBSkillDataList::skills_size() const {
  return skills_.size();
}
inline void DBSkillDataList::clear_skills() {
  skills_.Clear();
}
inline const ::google::protobuf::Map< ::google::protobuf::int32, ::DBSkillData >&
DBSkillDataList::skills() const {
  // @@protoc_insertion_point(field_map:DBSkillDataList.skills)
  return skills_.GetMap();
}
inline ::google::protobuf::Map< ::google::protobuf::int32, ::DBSkillData >*
DBSkillDataList::mutable_skills() {
  // @@protoc_insertion_point(field_mutable_map:DBSkillDataList.skills)
  return skills_.MutableMap();
}

// -------------------------------------------------------------------

// DBTaskData

// int32 task_id = 1;
inline void DBTaskData::clear_task_id() {
  task_id_ = 0;
}
inline ::google::protobuf::int32 DBTaskData::task_id() const {
  // @@protoc_insertion_point(field_get:DBTaskData.task_id)
  return task_id_;
}
inline void DBTaskData::set_task_id(::google::protobuf::int32 value) {
  
  task_id_ = value;
  // @@protoc_insertion_point(field_set:DBTaskData.task_id)
}

// int32 task_state = 2;
inline void DBTaskData::clear_task_state() {
  task_state_ = 0;
}
inline ::google::protobuf::int32 DBTaskData::task_state() const {
  // @@protoc_insertion_point(field_get:DBTaskData.task_state)
  return task_state_;
}
inline void DBTaskData::set_task_state(::google::protobuf::int32 value) {
  
  task_state_ = value;
  // @@protoc_insertion_point(field_set:DBTaskData.task_state)
}

// int32 task_param = 3;
inline void DBTaskData::clear_task_param() {
  task_param_ = 0;
}
inline ::google::protobuf::int32 DBTaskData::task_param() const {
  // @@protoc_insertion_point(field_get:DBTaskData.task_param)
  return task_param_;
}
inline void DBTaskData::set_task_param(::google::protobuf::int32 value) {
  
  task_param_ = value;
  // @@protoc_insertion_point(field_set:DBTaskData.task_param)
}

// int32 task_param2 = 4;
inline void DBTaskData::clear_task_param2() {
  task_param2_ = 0;
}
inline ::google::protobuf::int32 DBTaskData::task_param2() const {
  // @@protoc_insertion_point(field_get:DBTaskData.task_param2)
  return task_param2_;
}
inline void DBTaskData::set_task_param2(::google::protobuf::int32 value) {
  
  task_param2_ = value;
  // @@protoc_insertion_point(field_set:DBTaskData.task_param2)
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// DBTaskDataList

// map<int32, .DBTaskData> tasks = 1;
inline int DBTaskDataList::tasks_size() const {
  return tasks_.size();
}
inline void DBTaskDataList::clear_tasks() {
  tasks_.Clear();
}
inline const ::google::protobuf::Map< ::google::protobuf::int32, ::DBTaskData >&
DBTaskDataList::tasks() const {
  // @@protoc_insertion_point(field_map:DBTaskDataList.tasks)
  return tasks_.GetMap();
}
inline ::google::protobuf::Map< ::google::protobuf::int32, ::DBTaskData >*
DBTaskDataList::mutable_tasks() {
  // @@protoc_insertion_point(field_mutable_map:DBTaskDataList.tasks)
  return tasks_.MutableMap();
}

// -------------------------------------------------------------------

// DBDailyTaskData

// int32 task_id = 1;
inline void DBDailyTaskData::clear_task_id() {
  task_id_ = 0;
}
inline ::google::protobuf::int32 DBDailyTaskData::task_id() const {
  // @@protoc_insertion_point(field_get:DBDailyTaskData.task_id)
  return task_id_;
}
inline void DBDailyTaskData::set_task_id(::google::protobuf::int32 value) {
  
  task_id_ = value;
  // @@protoc_insertion_point(field_set:DBDailyTaskData.task_id)
}

// int32 task_state = 2;
inline void DBDailyTaskData::clear_task_state() {
  task_state_ = 0;
}
inline ::google::protobuf::int32 DBDailyTaskData::task_state() const {
  // @@protoc_insertion_point(field_get:DBDailyTaskData.task_state)
  return task_state_;
}
inline void DBDailyTaskData::set_task_state(::google::protobuf::int32 value) {
  
  task_state_ = value;
  // @@protoc_insertion_point(field_set:DBDailyTaskData.task_state)
}

// int32 task_param = 3;
inline void DBDailyTaskData::clear_task_param() {
  task_param_ = 0;
}
inline ::google::protobuf::int32 DBDailyTaskData::task_param() const {
  // @@protoc_insertion_point(field_get:DBDailyTaskData.task_param)
  return task_param_;
}
inline void DBDailyTaskData::set_task_param(::google::protobuf::int32 value) {
  
  task_param_ = value;
  // @@protoc_insertion_point(field_set:DBDailyTaskData.task_param)
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// DBDailyTaskDataList

// map<int32, .DBDailyTaskData> daily_tasks = 1;
inline int DBDailyTaskDataList::daily_tasks_size() const {
  return daily_tasks_.size();
}
inline void DBDailyTaskDataList::clear_daily_tasks() {
  daily_tasks_.Clear();
}
inline const ::google::protobuf::Map< ::google::protobuf::int32, ::DBDailyTaskData >&
DBDailyTaskDataList::daily_tasks() const {
  // @@protoc_insertion_point(field_map:DBDailyTaskDataList.daily_tasks)
  return daily_tasks_.GetMap();
}
inline ::google::protobuf::Map< ::google::protobuf::int32, ::DBDailyTaskData >*
DBDailyTaskDataList::mutable_daily_tasks() {
  // @@protoc_insertion_point(field_mutable_map:DBDailyTaskDataList.daily_tasks)
  return daily_tasks_.MutableMap();
}

// -------------------------------------------------------------------

// DBActivityData

// int32 activity_id = 1;
inline void DBActivityData::clear_activity_id() {
  activity_id_ = 0;
}
inline ::google::protobuf::int32 DBActivityData::activity_id() const {
  // @@protoc_insertion_point(field_get:DBActivityData.activity_id)
  return activity_id_;
}
inline void DBActivityData::set_activity_id(::google::protobuf::int32 value) {
  
  activity_id_ = value;
  // @@protoc_insertion_point(field_set:DBActivityData.activity_id)
}

// int32 activity_state = 2;
inline void DBActivityData::clear_activity_state() {
  activity_state_ = 0;
}
inline ::google::protobuf::int32 DBActivityData::activity_state() const {
  // @@protoc_insertion_point(field_get:DBActivityData.activity_state)
  return activity_state_;
}
inline void DBActivityData::set_activity_state(::google::protobuf::int32 value) {
  
  activity_state_ = value;
  // @@protoc_insertion_point(field_set:DBActivityData.activity_state)
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// DBActivitiesDataList

// map<int32, .DBActivityData> activities = 1;
inline int DBActivitiesDataList::activities_size() const {
  return activities_.size();
}
inline void DBActivitiesDataList::clear_activities() {
  activities_.Clear();
}
inline const ::google::protobuf::Map< ::google::protobuf::int32, ::DBActivityData >&
DBActivitiesDataList::activities() const {
  // @@protoc_insertion_point(field_map:DBActivitiesDataList.activities)
  return activities_.GetMap();
}
inline ::google::protobuf::Map< ::google::protobuf::int32, ::DBActivityData >*
DBActivitiesDataList::mutable_activities() {
  // @@protoc_insertion_point(field_mutable_map:DBActivitiesDataList.activities)
  return activities_.MutableMap();
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_db_5fstruct_2eproto__INCLUDED
