export TOP_DIR = $(PWD)/..
export SERVER_DIR = $(TOP_DIR)/db_server
export SERVER_BINDIR = $(TOP_DIR)/bin/db_server
export SERVER_EXE = db_server
export BOOST_LIBS = -lboost_system -lboost_thread
export OTHER_LIBS = $(TOP_DIR)/thirdparty/lib/mysql/libmysqlclient.a
include $(TOP_DIR)/common.mk
