export TOP_DIR = $(PWD)/..
export APP_DIR = $(TOP_DIR)/test_client
export APP_BINDIR = $(TOP_DIR)/bin/test_client
export APP_EXE = test_client 
export BOOST_LIBS = -lboost_system -lboost_coroutine -lboost_context -lboost_thread
include $(TOP_DIR)/common.mk
