export TOP_DIR = $(PWD)/..
export APP_DIR = $(TOP_DIR)/game_server
export APP_BINDIR = $(TOP_DIR)/bin/game_server
export APP_EXE = game_server
export BOOST_LIBS = -lboost_system -lboost_thread
include $(PWD)/../common.mk
